# Generated by Django 3.0.4 on 2020-03-24 16:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoservice',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
