# Generated by Django 3.0.4 on 2020-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0002_auto_20200324_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
