# Generated by Django 3.0.4 on 2020-03-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0004_auto_20200325_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='burnoe_app.CategoryService', verbose_name='Категория'),
        ),
    ]
