# Generated by Django 3.0.4 on 2020-03-25 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0005_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='burnoe_app.CategoryService', verbose_name='Категория'),
        ),
    ]
