# Generated by Django 3.0.4 on 2020-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0006_auto_20200325_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='order',
            field=models.IntegerField(default=10, verbose_name='Порядок'),
        ),
    ]
