# Generated by Django 3.0.4 on 2020-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0007_auto_20200325_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='row',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='row',
            name='order',
            field=models.IntegerField(default=10, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='row',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='row',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Короткое описание'),
        ),
    ]
