# Generated by Django 3.0.4 on 2020-05-03 17:56

import burnoe_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0010_auto_20200503_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_date',
            field=models.DateTimeField(default=burnoe_app.models.after, verbose_name='Дата удаления'),
        ),
    ]
