# Generated by Django 3.0.4 on 2020-05-04 10:26

import burnoe_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0011_auto_20200503_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_date',
            field=models.DateTimeField(default=burnoe_app.models.after_advert, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='service',
            name='last_date',
            field=models.DateTimeField(default=burnoe_app.models.after_advert, verbose_name='Дата удаления'),
        ),
    ]
