# Generated by Django 3.0.4 on 2020-05-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0012_auto_20200504_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_date']},
        ),
    ]
