# Generated by Django 3.0.4 on 2020-05-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0014_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'News'},
        ),
    ]
