# Generated by Django 3.0.4 on 2020-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0015_auto_20200507_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20, verbose_name='Заголовок 1')),
                ('name2', models.CharField(max_length=20, verbose_name='Заголовок 2')),
                ('last_date', models.DateTimeField(verbose_name='Дата событии')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'ordering': ['last_date'],
            },
        ),
    ]
