# Generated by Django 3.0.4 on 2020-05-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0017_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
