# Generated by Django 3.0.4 on 2020-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0018_auto_20200528_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default='https://instagram.com'),
        ),
    ]
