# Generated by Django 3.0.4 on 2020-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0022_auto_20200530_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='elect_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата (избранный)'),
        ),
        migrations.AddField(
            model_name='service',
            name='only',
            field=models.BooleanField(default=False, verbose_name='Единственный'),
        ),
    ]
