# Generated by Django 3.0.4 on 2020-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0023_auto_20200530_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
