# Generated by Django 3.0.4 on 2020-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0024_auto_20200530_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='icon_name',
            field=models.CharField(default='default_icon.svg', max_length=100),
        ),
    ]
