# Generated by Django 3.0.4 on 2020-09-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0025_servicecategory_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='Запрос')),
                ('count', models.IntegerField(default=0, verbose_name='Количество запросов')),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
