# Generated by Django 3.0.4 on 2020-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0026_searchquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60, unique=True, verbose_name='Тег')),
                ('alternative_text', models.TextField(verbose_name='Похожие')),
                ('count', models.IntegerField(default=0, verbose_name='Количество запросов')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-count'], 'verbose_name_plural': 'SearchQueries'},
        ),
        migrations.AddField(
            model_name='searchquery',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
