# Generated by Django 3.0.4 on 2020-09-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0027_auto_20200912_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(to='burnoe_app.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='alternative_text',
            field=models.TextField(blank=True, null=True, verbose_name='Похожие'),
        ),
    ]
