# Generated by Django 3.0.4 on 2020-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0028_auto_20200912_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='elect_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата избранный'),
        ),
    ]
