# Generated by Django 3.0.4 on 2020-09-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0029_auto_20200912_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchQuery',
            new_name='SearchText',
        ),
    ]
