# Generated by Django 3.0.4 on 2020-09-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0030_auto_20200913_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='only',
            new_name='is_monopolist',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='elect_date',
            new_name='last_best_date',
        ),
    ]
