# Generated by Django 3.0.4 on 2020-09-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0031_auto_20200916_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='MomentAdvert',
        ),
    ]
