# Generated by Django 3.0.4 on 2020-09-16 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0032_auto_20200916_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link_suff', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='contact',
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burnoe_app.Service')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='burnoe_app.ContactType')),
            ],
        ),
    ]
