# Generated by Django 3.0.4 on 2020-09-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0033_auto_20200916_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_monopolist',
            field=models.BooleanField(default=False, verbose_name='Единственный в районе'),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_best_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Избранный до'),
        ),
    ]
