# Generated by Django 3.0.4 on 2020-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0034_auto_20200917_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentadvert',
            name='name',
            field=models.CharField(max_length=21, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='momentadvert',
            name='phone',
            field=models.CharField(max_length=21, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='momentadvert',
            name='price',
            field=models.CharField(max_length=21, verbose_name='Цена'),
        ),
    ]
