# Generated by Django 3.0.4 on 2020-09-18 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0035_auto_20200917_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchtext',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='searchtext',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchtext',
            name='text',
            field=models.CharField(max_length=100, unique_for_date='created_date', verbose_name='Запрос'),
        ),
    ]
