# Generated by Django 3.0.4 on 2020-09-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0036_auto_20200918_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchtext',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Search Texts'},
        ),
    ]
