# Generated by Django 3.0.4 on 2020-09-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnoe_app', '0037_auto_20200918_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='burnoe_app.ServiceCategory'),
        ),
    ]
